### ISSUE TITLE
Issue in installing

### ISSUE THREAD

**Issue by cooltrooper** [shauser/mkdocs-pdf-export-plugin#11]
```
pip install mkdocs-pdf-export-plugin

Collecting mkdocs-pdf-export-plugin
  Could not find a version that satisfies the requirement mkdocs-pdf-export-plugin (from versions: )
No matching distribution found for mkdocs-pdf-export-plugin
```

**Comment by shauser** [comment]
Which python version are you using? The plugin currently works with Python 3.4 or higher only.

**Comment by cooltrooper** [comment]
I have both installed, so i assume pip is using the wrong version?

**Comment by shauser** [comment]
The easiest way to use pip is by using virtualenv. You can define which version of python to use when creating the virtualenv:

    virtualenv ./venv/ --python python3
    source ./venv/bin/activate
    pip install mkdocs mkdocs-pdf-export-plugin
    mkdocs build

More information is available here: https://virtualenv.pypa.io/en/stable/installation/

**Comment by cooltrooper** [comment]
I'll look into it thanks! Could you add it on the requirements list?
