### ISSUE TITLE
Unrecognised configuration name: plugins

### ISSUE THREAD

**Issue by gmm05126** [shauser/mkdocs-pdf-export-plugin#15]
Dear developers,

I installed you plugin using pip3 as suggested. While serving mkdocs I am getting the following:

`WARNING -  Config value: 'plugins'. Warning: Unrecognised configuration name: plugins`

Could you guide me to make your plugin work?
Thanks,
Martin

**Comment by shauser** [comment]
Please attach / post your full mkdocs.yml file.

**Comment by gmm05126** [comment]
Here is my mkdocs.yml

site_name: title

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

plugins:
    - search
    - pdf-export

**Comment by shauser** [comment]
Sorry for the delayed response. What version of mkdocs are you using? We are using the standard mkdocs plugin infrastructure, so this should actually work just out of the box. You might get better responses from the mkdocs support channels though.

**Comment by shauser** [comment]
Closing, seems to be an issue with mkdocs rather than this plugin.
