### ISSUE TITLE
When combined, resulting PDF is not in correct page order

### ISSUE THREAD

**Issue by cdbierl** [shauser/mkdocs-pdf-export-plugin#23]
I have a project that uses sub-folders under the docs folder to organize the markdown files. Could this be throwing off the order of the pages in the resulting PDF? I would expect the PDF to be consistent with the ordering in the mkdocs.yml "nav" entry.

Also when using the custom "@page" stylesheet, the page numbers seem to start over. Perhaps this is also due to the sub-folders being used?

**Comment by zhaoterryy** [comment]
I made the PR for this feature. The pages are in no particular order, I have no clue how it's determining the arrangement. When/if I have time I will look into this, it would make sense for the ordering to be consistent with the "nav" config.

@shauser let me know if you have any insight on this!
